M48
; DRILL file {KiCad 9.0.6} date 2026-03-12T20:15:04+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-12T20:15:04+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.500
%
G90
G05
T1
X135.0Y-87.5
X135.0Y-162.0
X227.0Y-87.5
X227.0Y-162.5
T2
X188.56Y-91.7
X188.56Y-121.4
X220.06Y-91.7
X220.06Y-121.4
T3
X157.13Y-127.5
X173.2Y-112.12
X203.57Y-130.0
M30
